[package]
name = "forge-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
iced = { workspace = true }
serde_json = { workspace = true }
forge-types = { path = "../forge-types" }
forge-events = { path = "../forge-events" }
forge-platform-core = { path = "../forge-platform-core" }
forge-script = { path = "../forge-script" }
fluent = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
time = { workspace = true }
