[package]
name                  = "forge-platform-twitch"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
repository.workspace  = true
rust-version.workspace = true

[lints]
workspace = true

[dev-dependencies]
forge-storage-sqlite = { path = "../forge-storage-sqlite" }
tracing-subscriber   = { workspace = true }

[dependencies]
forge-types          = { path = "../forge-types" }
forge-events         = { path = "../forge-events" }
forge-runtime        = { path = "../forge-runtime" }
forge-storage        = { path = "../forge-storage" }
forge-platform-core  = { path = "../forge-platform-core" }
tokio               = { workspace = true }
tokio-stream        = { workspace = true }
tokio-tungstenite   = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
thiserror           = { workspace = true }
async-trait         = { workspace = true }
tracing             = { workspace = true }
time                = { workspace = true }
reqwest             = { workspace = true }
rand                = { workspace = true }
futures-util        = { workspace = true }
twitch_api          = { workspace = true }
