use iced::widget::svg;
use iced::{Color, Element};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Icon {
    Home,
    Clock,
    Bolt,
    Terminal,
    Broadcast,
    LayoutGrid,
    Volume,
    Music,
    FileCode,
    Server,
    Notebook,
    Settings,
    Users,
    MessageCircle,
    Globe,
    Activity,
    Variable,
    ChevronDown,
    ChevronUp,
    ChevronRight,
    Download,
    Plus,
    Repeat,
    Eye,
    EyeOff,
    Copy,
    Refresh,
    AlertTriangle,
    Lock,
    X,
    CircleCheck,
    InfoCircle,
    Keyboard,
    Folder,
    FolderOpen,
    Photo,
    ExternalLink,
    PlayerPause,
    PlayerPlay,
    Eraser,
    DotsVertical,
    CircleDashed,
    Loader2,
    CircleX,
    ArrowBackUp,
    Star,
    Flag,
    LayoutSidebar,
}

impl Icon {
    fn bytes(self) -> &'static [u8] {
        match self {
            Icon::Home => include_bytes!("../assets/icons/tabler/home.svg"),
            Icon::Clock => include_bytes!("../assets/icons/tabler/clock.svg"),
            Icon::Bolt => include_bytes!("../assets/icons/tabler/bolt.svg"),
            Icon::Terminal => include_bytes!("../assets/icons/tabler/terminal-2.svg"),
            Icon::Broadcast => include_bytes!("../assets/icons/tabler/broadcast.svg"),
            Icon::LayoutGrid => include_bytes!("../assets/icons/tabler/layout-grid.svg"),
            Icon::Volume => include_bytes!("../assets/icons/tabler/volume.svg"),
            Icon::Music => include_bytes!("../assets/icons/tabler/music.svg"),
            Icon::FileCode => include_bytes!("../assets/icons/tabler/file-code.svg"),
            Icon::Server => include_bytes!("../assets/icons/tabler/server.svg"),
            Icon::Notebook => include_bytes!("../assets/icons/tabler/notebook.svg"),
            Icon::Settings => include_bytes!("../assets/icons/tabler/settings.svg"),
            Icon::Users => include_bytes!("../assets/icons/tabler/users.svg"),
            Icon::MessageCircle => include_bytes!("../assets/icons/tabler/message-circle.svg"),
            Icon::Globe => include_bytes!("../assets/icons/tabler/globe.svg"),
            Icon::Activity => include_bytes!("../assets/icons/tabler/activity.svg"),
            Icon::Variable => include_bytes!("../assets/icons/tabler/variable.svg"),
            Icon::ChevronDown => include_bytes!("../assets/icons/tabler/chevron-down.svg"),
            Icon::ChevronUp => include_bytes!("../assets/icons/tabler/chevron-up.svg"),
            Icon::ChevronRight => include_bytes!("../assets/icons/tabler/chevron-right.svg"),
            Icon::Download => include_bytes!("../assets/icons/tabler/download.svg"),
            Icon::Plus => include_bytes!("../assets/icons/tabler/plus.svg"),
            Icon::Repeat => include_bytes!("../assets/icons/tabler/repeat.svg"),
            Icon::Eye => include_bytes!("../assets/icons/tabler/eye.svg"),
            Icon::EyeOff => include_bytes!("../assets/icons/tabler/eye-off.svg"),
            Icon::Copy => include_bytes!("../assets/icons/tabler/copy.svg"),
            Icon::Refresh => include_bytes!("../assets/icons/tabler/refresh.svg"),
            Icon::AlertTriangle => include_bytes!("../assets/icons/tabler/alert-triangle.svg"),
            Icon::Lock => include_bytes!("../assets/icons/tabler/lock.svg"),
            Icon::X => include_bytes!("../assets/icons/tabler/x.svg"),
            Icon::CircleCheck => include_bytes!("../assets/icons/tabler/circle-check.svg"),
            Icon::InfoCircle => include_bytes!("../assets/icons/tabler/info-circle.svg"),
            Icon::Keyboard => include_bytes!("../assets/icons/tabler/keyboard.svg"),
            Icon::Folder => include_bytes!("../assets/icons/tabler/folder.svg"),
            Icon::FolderOpen => include_bytes!("../assets/icons/tabler/folder-open.svg"),
            Icon::Photo => include_bytes!("../assets/icons/tabler/photo.svg"),
            Icon::ExternalLink => include_bytes!("../assets/icons/tabler/external-link.svg"),
            Icon::PlayerPause => include_bytes!("../assets/icons/tabler/player-pause.svg"),
            Icon::PlayerPlay => include_bytes!("../assets/icons/tabler/player-play.svg"),
            Icon::Eraser => include_bytes!("../assets/icons/tabler/eraser.svg"),
            Icon::DotsVertical => include_bytes!("../assets/icons/tabler/dots-vertical.svg"),
            Icon::CircleDashed => include_bytes!("../assets/icons/tabler/circle-dashed.svg"),
            Icon::Loader2 => include_bytes!("../assets/icons/tabler/loader-2.svg"),
            Icon::CircleX => include_bytes!("../assets/icons/tabler/circle-x.svg"),
            Icon::ArrowBackUp => include_bytes!("../assets/icons/tabler/arrow-back-up.svg"),
            Icon::Star => include_bytes!("../assets/icons/tabler/star.svg"),
            Icon::Flag => include_bytes!("../assets/icons/tabler/flag.svg"),
            Icon::LayoutSidebar => include_bytes!("../assets/icons/tabler/layout-sidebar.svg"),
        }
    }

    pub fn from_name(name: &str) -> Self {
        match name {
            "home" => Icon::Home,
            "clock" => Icon::Clock,
            "bolt" | "lightning" => Icon::Bolt,
            "terminal" | "terminal-2" => Icon::Terminal,
            "broadcast" | "device-desktop" | "stack-2" | "record" | "brand-twitch" | "twitch"
            | "brand-obs" | "obs" => Icon::Broadcast,
            "layout-grid" | "grid" | "apps" => Icon::LayoutGrid,
            "volume" | "speaker" => Icon::Volume,
            "music" => Icon::Music,
            "file-code" => Icon::FileCode,
            "server" => Icon::Server,
            "notebook" | "journal" | "logs" => Icon::Notebook,
            "settings" | "gear" => Icon::Settings,
            "users" | "people" => Icon::Users,
            "message-circle" | "chat" => Icon::MessageCircle,
            "globe" => Icon::Globe,
            "activity" | "rss" => Icon::Activity,
            "variable" | "hash" => Icon::Variable,
            "chevron-down" => Icon::ChevronDown,
            "chevron-up" => Icon::ChevronUp,
            "chevron-right" | "send" => Icon::ChevronRight,
            "download" => Icon::Download,
            "plus" => Icon::Plus,
            "repeat" | "replay" | "arrows-shuffle" => Icon::Repeat,
            "eye" => Icon::Eye,
            "eye-off" | "eye-slash" => Icon::EyeOff,
            "copy" => Icon::Copy,
            "refresh" => Icon::Refresh,
            "loader" | "loader-2" => Icon::Loader2,
            "alert-triangle" | "warning" => Icon::AlertTriangle,
            "lock" | "key" => Icon::Lock,
            "x" | "close" => Icon::X,
            "circle-check" | "check" | "check-circle" | "shield-check" | "circle" => {
                Icon::CircleCheck
            }
            "info-circle" | "info" | "list" | "edit" | "pencil" | "flag-alert" => Icon::InfoCircle,
            "keyboard" => Icon::Keyboard,
            "folder" => Icon::Folder,
            "folder-open" => Icon::FolderOpen,
            "photo" | "file-image" | "image" | "camera" | "file-photo" => Icon::Photo,
            "external-link" | "external" => Icon::ExternalLink,
            "player-pause" | "pause" => Icon::PlayerPause,
            "player-play" | "play" => Icon::PlayerPlay,
            "eraser" => Icon::Eraser,
            "dots-vertical" => Icon::DotsVertical,
            "circle-dashed" => Icon::CircleDashed,
            "circle-x" | "x-circle" => Icon::CircleX,
            "arrow-back-up" | "rotate-ccw" | "undo" | "arrow-counterclockwise" => Icon::ArrowBackUp,
            "star" | "star-fill" => Icon::Star,
            "flag" | "flag-fill" => Icon::Flag,
            "layout-sidebar"
            | "sidebar"
            | "layout-sidebar-right"
            | "layout-sidebar-right-collapse" => Icon::LayoutSidebar,
            _ => Icon::InfoCircle,
        }
    }
}

pub fn tabler_icon<'a, Msg: 'a>(icon: Icon, size: f32, color: Color) -> Element<'a, Msg> {
    let handle = svg::Handle::from_memory(icon.bytes());
    svg::Svg::new(handle)
        .width(iced::Length::Fixed(size))
        .height(iced::Length::Fixed(size))
        .style(move |_theme: &iced::Theme, _status: svg::Status| svg::Style { color: Some(color) })
        .into()
}
