pub mod auth;
pub mod client;
pub mod content;
mod control;
pub mod credentials;
pub mod error;
pub mod events;
pub mod health;
pub mod protocol;
pub mod quick_actions;
pub(crate) mod request;
pub mod runners;
pub mod sink;
mod sink_impl;
pub mod status;
pub(crate) mod supervisor;
pub mod switchable_sink;
pub mod triggers;

pub use auth::AuthState;
pub use client::{VTubeClient, VTubeConfig};
pub use credentials::{VTUBE_CREDENTIAL_ID, VTubeConnectError, VTubeCredentials};
pub use error::VTubeError;
pub use runners::register_vtube_sub_actions;
pub use sink::VTubeSink;
pub use switchable_sink::SwitchableVTubeSink;
pub use triggers::register_vtube_triggers;
