[package]
name                   = "forge-obs"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
forge-events        = { path = "../forge-events" }
forge-platform-core = { path = "../forge-platform-core" }
forge-types         = { path = "../forge-types" }

obws         = { version = "0.15", features = ["events"] }
tokio        = { workspace = true }
tokio-stream = { workspace = true }
time         = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
async-trait  = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
rand         = { workspace = true }
